export const GET_INDIANTVSHOWS = "GET_INDIANTVSHOWS"
export const GET_HORRORTVSHOWS = "GET_HORRORTVSHOWS"
export const GET_ROMANCETVSHOWS = "GET_ROMANCETVSHOWS"
export const GET_DOCUSERIESSHOWS = "GET_DOCUSERIESSHOWS"
export const GET_BOLLYWOOD = "GET_BOLLYWOO"
export const GET_HOLLYWOOD = "GET_HOLLYWOOD"
export const GET_ANIME = "GET_ANIME"
export const GET_AWARDWINNING = "GET_AWARDWINNING"
export const Get_TVSHOWS = "Get_TVSHOWS"
export const Get_MOVIES = "Get_MOVIES"

export const EMAIL = "EMAIL"
export const PASSWORD = "PASSWORD"
export const GETUserDATA = "GETUserDATA"
export const MAINITEM = "MAINITEM"
export const CATEGORY = "CATEGORY"
export const ENDCATEGORY = "ENDCATEGORY"
export const SEARCH = "SEARCH"
export const SEARCHDATA = "SEARCHDATA"

export const LOADING = "LOADING"
export const ERROR = "ERROR"

export const SIGNIN_LOADING= "SIGNIN_LOGIN"
export const SIGNIN_ERROR= "SIGNIN_ERROR"

export const USERLOGIN = "USERLOGIN"
export const USERLOGOUT = "USERLOGOUT"
